/* Main.c file generated by New Project wizard
 *
 * Created:   Fri Oct 22 2021
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include "config.h"
#include <stdlib.h>
#include <time.h>
#define _XTAL_FREQ 8388608

int n0 = 0b10000000;	// .
int n1 = 0b10000000;	// .
int n2 = 0b01011100;	//o
int n3 = 0b00111101;	//G
int sum = 0, b = 0, c = 0;
int compt;


int _ss_display(int n)
{
   if (n == 0) return 0b00111111;
   if (n == 1) return 0b00000110;
   if (n == 2) return 0b01011011;
   if (n == 3) return 0b01001111;	 
   if (n == 4) return 0b01100110;
   if (n == 5) return 0b01101101;
   if (n == 6) return 0b01111101;
   if (n == 7) return 0b00000111;
   if (n == 8) return 0b01111111;
   if (n == 9) return 0b01101111;
   return 0b11111111;
}

void interrupt high_priority_service(void)
{
   if (INT0IE && INT0IF)
   {
      n0 = n1 = n2 = n3 = 0b00001000;
      INT0IE = 0;
      __delay_ms(2);
      INT1IE = 1;
      INT1IF = 0;
      n0 = n1 = n2 = n3 = 0b00001000;
   }
   else if (INT1IE && INT1IF && !b)
   {
      srand(compt);
      int var = rand()%6 + 1;
      if (n0 == 0b00001000){
	 n0 = _ss_display(var); 		
	 __delay_ms(2);
	 INT1IF = 0;
      }
      else if (n1 == 0b00001000){	
	 n1 = _ss_display(var); 		
	 __delay_ms(2);
	 INT1IF = 0;
      }
      else if (n2 == 0b00001000){
	 n2 = _ss_display(var); 		
	 __delay_ms(2);
	 INT1IF = 0;
      }
      else if (n3 == 0b00001000){
	 n3 = _ss_display(var); 		
	 __delay_ms(2);
	 INT1IF = INT2IF = 0;
	 INT0IE = INT1IE = 0;
	 INT2IE = 1;
      }
      sum += var;
   }
   else if (INT2IE && INT2IF)
   {
      n0 = _ss_display(sum%10);
      n1 = _ss_display((sum/10)%10);
      n2 = 0b01001000;
      n3 = 0b01110110;
      sum = 0;
      INT2IE = INT1IF = INT0IF = INT2IF = 0;
      INT0IE = 1;
   }
}

void interrupt low_priority low_priority_service(void)
{}

void main(void)
 {
   // Write your code here
    ANSELA = 0;			// Set port to digital
    ANSELB = 0;			// Set port to digital
    ANSELD = 0;			// Set port to digital
    TRISA = 0;			// Set port to output
    TRISB = 0xFF;		// Set port to input
    TRISD = 0;			// Set port to output	
    
    GIEH = 1;			// Global high priority interrupt enable	
    GIEL = 1;			// Global low priority interrupt enable
    INT0IF = INT1IF = INT2IF = 0;	// Unable if flag to int0, int1 and int2
    INT0IE = 1;			// Enable interruption on int0
    INT1IE = INT2IE = 0;	// Unable interruption on int1 and int2
    
    INTEDG0 = 1;
    INTEDG1 = 1;
    INTEDG2 = 0;
    // Set priority 0->low, 1 -> high
    //INT0IP = 1;
    //INT1IP = 1;
    //INT2IP = 1;
    
    //Set random seed
    //srand(NULL);
    compt = 0;
    
   while (1) {
      PORTA = 1;
      PORTD = n0;
      __delay_ms(1);
      PORTA = 2;
      PORTD = n1;
      __delay_ms(1);
      PORTA = 4;
      PORTD = n2;
      __delay_ms(1);
      PORTA = 8;
      PORTD = n3;
      __delay_ms(1);
      ++compt;
   }
 }