;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Thu Sep 30 2021
; Processor: PIC18F45K22
; Compiler:  MPASM (Proteus)
;====================================================================

;===================================================================
; DEFINITIONS
;===================================================================
#include p18f45k22.inc      ; Include register definition file
   CONFIG FOSC = INTIO67    ; Use Internal Oscillator

;===================================================================
; RESET and INTERRUPT VECTORS
;===================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start

;===================================================================
; CODE SEGMENT
;===================================================================
PGM   code
Start
      MOVLB 0x0F       ;Triem els bank 0F on hi ha els SFR
      CLRF  ANSELA,1   ;Posem el PORTA en Digital
      CLRF  ANSELB,1   ;Posem el PORTB en Digital
      CLRF  ANSELC,1   ;Posem el PORTC en Digital
      
      SETF  TRISA,1     ;PORTA INPUT
      CLRF  TRISB,1     ;PORTB OUTPUT
      CLRF  TRISC,1     ;PORTC OUTPUT
      CLRF  PORTC,1     ;PORTC INIT a 0
Loop 
      INCF  PORTC, 1    ;Incrementar el registre associat a PORTC
      MOVF  PORTA, 0, 1 ;W=PORTA
      ;XORLW 1 ;ACTIVAR AQUESTA LINEA PER INVERTIR EL FUNCIONAMENT
      MOVWF PORTB, 1    ;PORTB=W
      NOP               ;No Operation
      NOP               ;No Operation
      goto  Loop

;===================================================================
      END
